"""
Django settings for AUdoc_back project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import secrets

# Load .env file if it exists (for local development)
_env_path = Path(__file__).resolve().parent.parent / ".env"
if _env_path.exists():
    with open(_env_path) as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate a secure random key if none is provided
_default_secret = os.environ.get("DJANGO_SECRET_KEY", "")
if not _default_secret:
    _secret_file = BASE_DIR / ".secret_key"
    if _secret_file.exists():
        _default_secret = _secret_file.read_text().strip()
    else:
        _default_secret = secrets.token_urlsafe(50)
        try:
            _secret_file.write_text(_default_secret)
        except (OSError, IOError):
            pass  # Running in read-only environment

SECRET_KEY = _default_secret

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")


_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    # Production: require explicit configuration
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "audoc.onrender.com"
    ]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://churlish-xerically-karren.ngrok-free.dev",
    "https://audoc.onrender.com"
]
# Add additional trusted origins from environment
_csrf_origins_env = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if _csrf_origins_env:
    CSRF_TRUSTED_ORIGINS.extend([o.strip() for o in _csrf_origins_env.split(",") if o.strip()])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AUdoc_back.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AUdoc_back.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Support SQLite (development), Render PostgreSQL (production), and custom PostgreSQL
if os.environ.get("DATABASE_URL"):
    # Render PostgreSQL (uses DATABASE_URL environment variable)
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ.get("DATABASE_URL"),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get("DB_ENGINE") == "postgresql":
    # Custom PostgreSQL setup
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "audoc_db"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL  = "/post-login/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL           = "/accounts/login/"

# ── Authentication backends ───────────────────────────────────────────────────
# StudentIDBackend first: lets students log in with Student ID (no password).
# ModelBackend second: lets staff/admin log in with username + password.
AUTHENTICATION_BACKENDS = [
    "app.backends.StudentIDBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# ── Email Configuration ──────────────────────────────────────────────────────
# Use Resend API (simplest email service for Render)
# Get key: https://resend.com/api-keys
EMAIL_BACKEND = "app.resend_backend.ResendBackend"
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
DEFAULT_FROM_EMAIL = "noreply@audoc.onrender.com"

# ── Groq AI (Chatbot — free tier) ───────────────────────────────────────────
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")

# ══════════════════════════════════════════════════════════════════════════════
#  SECURITY SETTINGS
# ══════════════════════════════════════════════════════════════════════════════

# ── Session Security ─────────────────────────────────────────────────────────
SESSION_COOKIE_SECURE = not DEBUG  # Only send cookies over HTTPS in production
SESSION_COOKIE_HTTPONLY = True     # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = "Lax"    # CSRF protection for session cookie
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ── CSRF Security ────────────────────────────────────────────────────────────
CSRF_COOKIE_SECURE = not DEBUG     # Only send CSRF cookie over HTTPS in production
CSRF_COOKIE_HTTPONLY = True        # Prevent JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = "Lax"       # Strict same-site policy
CSRF_FAILURE_VIEW = "django.views.csrf.csrf_failure"

# ── SSL/HTTPS Settings (Production) ──────────────────────────────────────────
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "False").lower() in ("true", "1", "yes")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ── Security Headers ─────────────────────────────────────────────────────────
SECURE_BROWSER_XSS_FILTER = True           # Enable XSS filter in browser
SECURE_CONTENT_TYPE_NOSNIFF = True         # Prevent content-type sniffing
X_FRAME_OPTIONS = "DENY"                   # Prevent clickjacking
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# HSTS (only enable in production with HTTPS)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000           # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ── API Security (Rate Limiting Configuration) ───────────────────────────────
# Rate limits: max requests per window (in seconds)
RATE_LIMIT_OTP = {
    "max_requests": 5,      # Max OTP requests
    "window_seconds": 300,  # Per 5-minute window
}
RATE_LIMIT_LOGIN = {
    "max_requests": 10,     # Max login attempts
    "window_seconds": 300,  # Per 5-minute window
}
RATE_LIMIT_API = {
    "max_requests": 100,    # Max API requests
    "window_seconds": 60,   # Per minute
}

# ── Content Security Policy ──────────────────────────────────────────────────
# Add this header via middleware or nginx in production
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://fonts.googleapis.com")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'", "https://api.groq.com")

# ── Password Hashing ─────────────────────────────────────────────────────────
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# ── Logging (Security Events) ────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "security_file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "security.log",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.security": {
            "handlers": ["security_file", "console"] if not DEBUG else ["console"],
            "level": "WARNING",
            "propagate": True,
        },
        "app.security": {
            "handlers": ["security_file", "console"] if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Create logs directory if it doesn't exist
_logs_dir = BASE_DIR / "logs"
if not _logs_dir.exists():
    try:
        _logs_dir.mkdir(parents=True, exist_ok=True)
    except (OSError, IOError):
        pass  # Running in read-only environment

# ══════════════════════════════════════════════════════════════════════════════
#  Razorpay Settings
# ══════════════════════════════════════════════════════════════════════════════
RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET", "")

# ══════════════════════════════════════════════════════════════════════════════
#  SMS & Notification Settings
# ══════════════════════════════════════════════════════════════════════════════
# SMS is OPTIONAL - use email-only for FREE (recommended for students!)
# To enable SMS, set SMS_PROVIDER to "twilio" or "nexmo" and add credentials

# SMS Provider: 'disabled' (free - default), 'twilio', or 'nexmo'
SMS_PROVIDER = os.environ.get("SMS_PROVIDER", "disabled")

# Twilio Configuration for SMS reminders
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER", "")

# Alternative: Nexmo/Vonage SMS
NEXMO_API_KEY = os.environ.get("NEXMO_API_KEY", "")
NEXMO_API_SECRET = os.environ.get("NEXMO_API_SECRET", "")
NEXMO_PHONE_NUMBER = os.environ.get("NEXMO_PHONE_NUMBER", "")

# Appointment Reminder Settings (hours before appointment)
APPOINTMENT_REMINDER_24H = True  # Send 24-hour email reminder (FREE)
APPOINTMENT_REMINDER_2H = True   # Send 2-hour SMS reminder (optional - requires SMS setup)

# No-Show Settings
NO_SHOW_THRESHOLD = 3  # Mark as restricted after N no-shows
NO_SHOW_RESTRICTION_DAYS = 30  # Restrict for N days
