# Generated by Django 4.2.25 on 2026-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=50, verbose_name="Student ID"),
                ),
                (
                    "student_name",
                    models.CharField(max_length=150, verbose_name="Student Name"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone No.")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "student_department",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("EEE", "Electrical & Electronic Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("CE", "Civil Engineering"),
                            ("TE", "Textile Engineering"),
                            ("IPE", "Industrial & Production Engineering"),
                            ("BBA", "Business Administration"),
                            ("ENG", "English"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Student Department",
                    ),
                ),
                (
                    "medical_department",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Physician"),
                            ("DENTAL", "Dental Care"),
                            ("EYE", "Eye Care"),
                            ("MENTAL", "Mental Health & Counseling"),
                            ("ORTHO", "Orthopedics"),
                            ("DERM", "Dermatology"),
                            ("GYNAE", "Gynecology"),
                            ("PHYSIO", "Physiotherapy"),
                        ],
                        max_length=20,
                        verbose_name="Department",
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(verbose_name="Description of Problem"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointment List",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Doctor Name")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20, verbose_name="Phone No.")),
                (
                    "specialized_in",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Physician"),
                            ("DENTAL", "Dental Care"),
                            ("EYE", "Eye Care"),
                            ("MENTAL", "Mental Health & Counseling"),
                            ("ORTHO", "Orthopedics"),
                            ("DERM", "Dermatology"),
                            ("GYNAE", "Gynecology"),
                            ("PHYSIO", "Physiotherapy"),
                        ],
                        max_length=20,
                        verbose_name="Specialized In",
                    ),
                ),
                (
                    "available_days",
                    models.CharField(
                        help_text="Hold Ctrl / Cmd to select multiple days",
                        max_length=200,
                        verbose_name="Available Days",
                    ),
                ),
                (
                    "available_time",
                    models.CharField(
                        help_text='e.g. "9:00 AM – 5:00 PM"',
                        max_length=100,
                        verbose_name="Available Time",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctor List",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
