# Generated by Django 4.2.25 on 2026-03-07 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_appointment_id_alter_doctor_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_student",
                    models.BooleanField(default=True, verbose_name="Is Student"),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if this user is not a student",
                        max_length=50,
                        verbose_name="Student ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone No.")),
                (
                    "emergency_contact",
                    models.CharField(
                        max_length=20, verbose_name="Emergency Contact No."
                    ),
                ),
                ("home_address", models.TextField(verbose_name="Home Address")),
                ("present_address", models.TextField(verbose_name="Present Address")),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("EEE", "Electrical & Electronic Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("CE", "Civil Engineering"),
                            ("TE", "Textile Engineering"),
                            ("IPE", "Industrial & Production Engineering"),
                            ("BBA", "Business Administration"),
                            ("ENG", "English"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Department",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=4,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registered User",
                "verbose_name_plural": "Registered Users",
                "ordering": ["user__username"],
            },
        ),
    ]
