# Generated by Django 4.2.25 on 2026-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        help_text='e.g. "STAFF-001"',
                        max_length=50,
                        unique=True,
                        verbose_name="Staff ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone No.")),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                (
                    "is_doctor",
                    models.BooleanField(default=False, verbose_name="Is Doctor"),
                ),
            ],
            options={
                "verbose_name": "Registered Staff",
                "verbose_name_plural": "Registered Staff",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "ordering": ["user__username"],
                "verbose_name": "Registered Student",
                "verbose_name_plural": "Registered Students",
            },
        ),
    ]
