# Generated by Django 6.0.3 on 2026-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_staffprofile_alter_studentprofile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "student_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Student ID"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone No.")),
                (
                    "emergency_contact",
                    models.CharField(
                        max_length=20, verbose_name="Emergency Contact No."
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("EEE", "Electrical & Electronic Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("CE", "Civil Engineering"),
                            ("TE", "Textile Engineering"),
                            ("IPE", "Industrial & Production Engineering"),
                            ("BBA", "Business Administration"),
                            ("ENG", "English"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Department",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=4,
                        verbose_name="Blood Group",
                    ),
                ),
                ("home_address", models.TextField(verbose_name="Home Address")),
                ("present_address", models.TextField(verbose_name="Present Address")),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registered At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Registration",
                "verbose_name_plural": "Student Registrations",
                "ordering": ["-registered_at"],
            },
        ),
    ]
