# Generated by Django 4.2.25 on 2026-03-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_studentregistration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="is_student",
            new_name="is_verified",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Verified"),
        ),
        migrations.RenameField(
            model_name="loginlog",
            old_name="is_student",
            new_name="is_verified",
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified"),
        ),
    ]
