# Generated by Django 4.2.25 on 2026-03-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_is_student_to_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Appointment Date"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("09:00 AM", "09:00 AM"),
                    ("09:30 AM", "09:30 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("10:30 AM", "10:30 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("01:00 PM", "01:00 PM"),
                    ("01:30 PM", "01:30 PM"),
                    ("02:00 PM", "02:00 PM"),
                    ("02:30 PM", "02:30 PM"),
                    ("03:00 PM", "03:00 PM"),
                    ("03:30 PM", "03:30 PM"),
                    ("04:00 PM", "04:00 PM"),
                    ("04:30 PM", "04:30 PM"),
                ],
                max_length=20,
                null=True,
                verbose_name="Preferred Time Slot",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="app.doctor",
                verbose_name="Preferred Doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="medical_department",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Physician"),
                    ("DENTAL", "Dental Care"),
                    ("EYE", "Eye Care"),
                    ("MENTAL", "Mental Health & Counseling"),
                    ("ORTHO", "Orthopedics"),
                    ("DERM", "Dermatology"),
                    ("GYNAE", "Gynecology"),
                    ("PHYSIO", "Physiotherapy"),
                ],
                max_length=20,
                verbose_name="Medical Department",
            ),
        ),
    ]
