# Generated by Django 4.2.25 on 2026-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_appointment_appointment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
