# Generated by Django 6.0.3 on 2026-03-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_appointment_add_completed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("09:00 AM", "09:00 AM"),
                    ("09:30 AM", "09:30 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("10:30 AM", "10:30 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("12:00 PM", "12:00 PM"),
                    ("12:30 PM", "12:30 PM"),
                    ("02:00 PM", "02:00 PM"),
                    ("02:30 PM", "02:30 PM"),
                    ("03:00 PM", "03:00 PM"),
                    ("03:30 PM", "03:30 PM"),
                    ("04:00 PM", "04:00 PM"),
                    ("04:30 PM", "04:30 PM"),
                ],
                max_length=20,
                null=True,
                verbose_name="Preferred Time Slot",
            ),
        ),
    ]
