# Generated by Django 4.2.25 on 2026-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_appointment_appointment_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=50, verbose_name="Student ID"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Donor Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount (BDT)"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Paid")),
                (
                    "donated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donation List",
                "ordering": ["-donated_at"],
            },
        ),
    ]
