# Generated by Django 4.2.25 on 2026-03-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Donor Name"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="student_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Student ID"
            ),
        ),
    ]
