# Generated by Django 4.2.25 on 2026-03-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_donation_email_alter_donation_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Student ID"
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(max_length=150, verbose_name="Donor Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone No.")),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=4,
                        verbose_name="Blood Group",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "weight",
                    models.PositiveIntegerField(
                        help_text="Minimum 50 kg required", verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "previous_donation",
                    models.BooleanField(
                        default=False, verbose_name="Have you donated blood before?"
                    ),
                ),
                (
                    "health_condition",
                    models.CharField(
                        blank=True,
                        help_text="e.g., diabetes, heart disease, etc.",
                        max_length=200,
                        verbose_name="Any medical conditions?",
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(verbose_name="Preferred Donation Date"),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Additional Message"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Donation",
                "verbose_name_plural": "Blood Donations",
                "ordering": ["-created_at"],
            },
        ),
    ]
