# Generated by Django 4.2.25 on 2026-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_blooddonation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Student ID"
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(max_length=150, verbose_name="Requester Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone No.")),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=4,
                        verbose_name="Blood Group Needed",
                    ),
                ),
                (
                    "units_required",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of blood units needed",
                        verbose_name="Units Required",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="e.g., Surgery, Accident, Transfusion, etc.",
                        max_length=200,
                        verbose_name="Reason for Request",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Urgency Level",
                    ),
                ),
                ("required_date", models.DateField(verbose_name="Date Needed By")),
                (
                    "hospital_name",
                    models.CharField(
                        help_text="Where the blood is needed",
                        max_length=200,
                        verbose_name="Hospital/Clinic Name",
                    ),
                ),
                (
                    "hospital_contact",
                    models.CharField(
                        max_length=200, verbose_name="Hospital Contact/Address"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("FULFILLED", "Fulfilled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Requested At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Request",
                "verbose_name_plural": "Blood Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
