# Generated by Django 4.2.25 on 2026-03-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_bloodrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="requested_donor",
            field=models.ForeignKey(
                blank=True,
                help_text="If requesting from a specific donor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_received",
                to="app.blooddonation",
                verbose_name="Requested From Donor",
            ),
        ),
    ]
