# Generated by Django 4.2.25 on 2026-03-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_bloodrequest_requested_donor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blooddonation",
            name="preferred_date",
        ),
    ]
