# Generated by Django 4.2.25 on 2026-03-12 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_blooddonation_preferred_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Response",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Responded At"
                    ),
                ),
                (
                    "blood_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor_responses",
                        to="app.bloodrequest",
                        verbose_name="Blood Request",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="app.blooddonation",
                        verbose_name="Donor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donor Response",
                "verbose_name_plural": "Donor Responses",
                "ordering": ["-blood_request__created_at"],
                "unique_together": {("blood_request", "donor")},
            },
        ),
    ]
