# Generated by Django 4.2.25 on 2026-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_donorresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpDesk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "apology_sent",
                    models.BooleanField(
                        default=False, verbose_name="Apology Email Sent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Desk Feedback",
                "verbose_name_plural": "Help Desk Feedback",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
