# Generated by Django 4.2.25 on 2026-03-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_helpdesk_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helpdesk",
            name="apology_sent",
        ),
        migrations.RemoveField(
            model_name="helpdesk",
            name="email",
        ),
    ]
