# Generated by Django 6.0.3 on 2026-03-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_appointment_student_department_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todaysappointment",
            options={
                "ordering": ["appointment__created_at"],
                "verbose_name": "Today's Appointment",
                "verbose_name_plural": "Today's Appointments",
            },
        ),
    ]
