# Generated by Django 6.0.3 on 2026-04-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_donation_razorpay_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="actual_completion_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actual Completion Time"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_24h_sent",
            field=models.BooleanField(
                default=False, verbose_name="24-Hour Reminder Sent"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_24h_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="24H Reminder Sent At"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_2h_sent",
            field=models.BooleanField(
                default=False, verbose_name="2-Hour Reminder Sent"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_2h_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="2H Reminder Sent At"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="was_no_show",
            field=models.BooleanField(default=False, verbose_name="No-Show"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="lunch_break_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Lunch Break End"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="lunch_break_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Lunch Break Start"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="working_hours_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Working Hours End"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="working_hours_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Working Hours Start"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("NO_SHOW", "No-Show"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="available_days",
            field=models.CharField(
                help_text="Hold Ctrl / Cmd to select multiple days (e.g., 'Monday, Tuesday, Wednesday, Thursday, Friday')",
                max_length=200,
                verbose_name="Available Days",
            ),
        ),
        migrations.CreateModel(
            name="DoctorLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_date_from", models.DateField(verbose_name="Leave From")),
                ("leave_date_to", models.DateField(verbose_name="Leave Till")),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal Leave"),
                            ("MEDICAL", "Medical Leave"),
                            ("CONFERENCE", "Conference/Training"),
                            ("EMERGENCY", "Emergency"),
                            ("OTHER", "Other"),
                        ],
                        default="PERSONAL",
                        max_length=20,
                        verbose_name="Leave Type",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="app.doctor",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Leave",
                "verbose_name_plural": "Doctor Leaves",
                "ordering": ["-leave_date_from"],
            },
        ),
        migrations.CreateModel(
            name="StudentNoShowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_no_shows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total No-Shows"
                    ),
                ),
                (
                    "last_no_show_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last No-Show Date"
                    ),
                ),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False, verbose_name="Restricted from Booking"
                    ),
                ),
                (
                    "restriction_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Restriction Until"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_show_record",
                        to="app.studentprofile",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student No-Show Record",
                "verbose_name_plural": "Student No-Show Records",
            },
        ),
    ]
