# Generated by Django 6.0.3 on 2026-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_appointment_actual_completion_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="oauth_id",
            field=models.CharField(
                blank=True,
                help_text="Google unique ID (sub claim) for OAuth logins",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="OAuth ID",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="oauth_provider",
            field=models.CharField(
                choices=[("password", "Password"), ("google", "Google")],
                default="password",
                help_text="Login method used",
                max_length=20,
                verbose_name="OAuth Provider",
            ),
        ),
    ]
