# Generated by Django 6.0.3 on 2026-05-03 06:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_studentprofile_oauth_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="doctor_id",
            field=models.CharField(
                default=app.models.generate_default_doctor_id,
                editable=False,
                help_text="Auto-generated ID (e.g., DOC4yt253)",
                max_length=20,
                unique=True,
                verbose_name="Doctor ID",
            ),
        ),
    ]
