# Generated by Django 6.0.3 on 2026-05-04 15:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_doctor_doctor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="staff_id",
            field=models.CharField(
                default=app.models.generate_default_staff_id,
                editable=False,
                help_text="Auto-generated ID (e.g., STAdwt4t4)",
                max_length=50,
                unique=True,
                verbose_name="Staff ID",
            ),
        ),
    ]
