# Generated by Django 6.0.3 on 2026-05-04 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_staffprofile_staff_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Already Used"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="app.staffprofile",
                        verbose_name="Staff Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Password Reset Token",
                "verbose_name_plural": "Staff Password Reset Tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
