# Generated by Django 6.0.3 on 2026-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_staffpasswordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.URLField(
                blank=True,
                help_text="Public URL of the doctor's profile photo (stored in Supabase Storage)",
                max_length=500,
                null=True,
                verbose_name="Profile Photo URL",
            ),
        ),
    ]
