# Generated by Django 6.0.3 on 2026-08-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_doctor_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Medicine Name"),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Acetaminophen for Paracetamol",
                        max_length=200,
                        verbose_name="Generic / Salt Name",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Painkiller, Antibiotic, Syrup, Ointment",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Manufacturer"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description / Usage Notes"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="Tablets",
                        help_text="e.g., Tablets, Capsules, Bottles, Strips, mL",
                        max_length=50,
                        verbose_name="Unit of Measurement",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicineStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Manufacturer batch/lot number",
                        max_length=100,
                        verbose_name="Batch Number",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Current Quantity"
                    ),
                ),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                ("received_date", models.DateField(verbose_name="Date Received")),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Supplier"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Purchase Price (₹)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="app.medicine",
                        verbose_name="Medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Stock",
                "verbose_name_plural": "Medicine Stocks",
                "ordering": ["expiry_date"],
                "unique_together": {("medicine", "batch_number")},
            },
        ),
    ]
