# Generated by Django 6.0.3 on 2026-08-18 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_medicine_medicinestock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineStockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ADD", "Addition"),
                            ("SUBTRACT", "Subtraction/Dispense"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Quantity Changed"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Transaction Date"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Reason/Notes"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="app.medicinestock",
                        verbose_name="Stock Batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Transaction",
                "verbose_name_plural": "Medicine Transactions",
                "ordering": ["-date"],
            },
        ),
    ]
