# Generated by Django 6.0.3 on 2026-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_medicinestocktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=10, verbose_name='Status'),
        ),
    ]
