# Generated by Django 6.0.3 on 2026-09-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_blooddonation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Verified / Approved'), ('PENDING', 'Unverified / Pending'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=10, verbose_name='Status'),
        ),
    ]
