# Generated by Django 6.0.3 on 2026-09-13 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_bloodrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='student_department',
            field=models.CharField(choices=[('LING', 'Linguistics'), ('BEN', 'Bengali'), ('HINDI', 'Hindi'), ('MANI', 'Manipuri'), ('SANS', 'Sanskrit'), ('ASM', 'Assamese'), ('ENG', 'English'), ('ARAB', 'Arabic'), ('FREN', 'French'), ('ECON', 'Economics'), ('COM', 'Commerce'), ('POLSCI', 'Political Science'), ('HIST', 'History'), ('SOCIO', 'Sociology'), ('SWRK', 'Social Work'), ('MASSCOM', 'Mass Communication'), ('VISART', 'Visual Arts'), ('PERART', 'Performing Arts'), ('PHIL', 'Philosophy'), ('EDU', 'Education'), ('BBA', 'Business Administration'), ('LIS', 'Library & Information Science'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematics'), ('STAT', 'Statistics'), ('CS', 'Computer Science'), ('LSBIO', 'Life Science & Bioinformatics'), ('MICRO', 'Microbiology'), ('BIOTECH', 'Biotechnology'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('CSC', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Telecommunication'), ('AGENG', 'Agricultural Engineering'), ('ECO', 'Ecology & Environmental Science'), ('EARTH', 'Earth Sciences'), ('LAW', 'Law'), ('PHARMA', 'Pharmaceutical Sciences'), ('OTHER', 'Other')], max_length=10, verbose_name='Student Department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('LING', 'Linguistics'), ('BEN', 'Bengali'), ('HINDI', 'Hindi'), ('MANI', 'Manipuri'), ('SANS', 'Sanskrit'), ('ASM', 'Assamese'), ('ENG', 'English'), ('ARAB', 'Arabic'), ('FREN', 'French'), ('ECON', 'Economics'), ('COM', 'Commerce'), ('POLSCI', 'Political Science'), ('HIST', 'History'), ('SOCIO', 'Sociology'), ('SWRK', 'Social Work'), ('MASSCOM', 'Mass Communication'), ('VISART', 'Visual Arts'), ('PERART', 'Performing Arts'), ('PHIL', 'Philosophy'), ('EDU', 'Education'), ('BBA', 'Business Administration'), ('LIS', 'Library & Information Science'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematics'), ('STAT', 'Statistics'), ('CS', 'Computer Science'), ('LSBIO', 'Life Science & Bioinformatics'), ('MICRO', 'Microbiology'), ('BIOTECH', 'Biotechnology'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('CSC', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Telecommunication'), ('AGENG', 'Agricultural Engineering'), ('ECO', 'Ecology & Environmental Science'), ('EARTH', 'Earth Sciences'), ('LAW', 'Law'), ('PHARMA', 'Pharmaceutical Sciences'), ('OTHER', 'Other')], max_length=10, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='department',
            field=models.CharField(choices=[('LING', 'Linguistics'), ('BEN', 'Bengali'), ('HINDI', 'Hindi'), ('MANI', 'Manipuri'), ('SANS', 'Sanskrit'), ('ASM', 'Assamese'), ('ENG', 'English'), ('ARAB', 'Arabic'), ('FREN', 'French'), ('ECON', 'Economics'), ('COM', 'Commerce'), ('POLSCI', 'Political Science'), ('HIST', 'History'), ('SOCIO', 'Sociology'), ('SWRK', 'Social Work'), ('MASSCOM', 'Mass Communication'), ('VISART', 'Visual Arts'), ('PERART', 'Performing Arts'), ('PHIL', 'Philosophy'), ('EDU', 'Education'), ('BBA', 'Business Administration'), ('LIS', 'Library & Information Science'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematics'), ('STAT', 'Statistics'), ('CS', 'Computer Science'), ('LSBIO', 'Life Science & Bioinformatics'), ('MICRO', 'Microbiology'), ('BIOTECH', 'Biotechnology'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('CSC', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Telecommunication'), ('AGENG', 'Agricultural Engineering'), ('ECO', 'Ecology & Environmental Science'), ('EARTH', 'Earth Sciences'), ('LAW', 'Law'), ('PHARMA', 'Pharmaceutical Sciences'), ('OTHER', 'Other')], max_length=10, verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(default='unknown', max_length=100, verbose_name='Model Used')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Prompt Tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Completion Tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total Tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Chat Log',
                'verbose_name_plural': 'AI Chat Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
