# Generated by Django 6.0.3 on 2026-09-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_appointment_student_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(max_length=200, verbose_name='Illness')),
                ('symptoms', models.TextField(verbose_name='Symptoms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='app.appointment', verbose_name='Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicalhistory')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='prescribed_in', through='app.PrescribedMedicine', to='app.medicine', verbose_name='Medicines Recommended'),
        ),
    ]
