# Generated by Django 6.0.3 on 2026-09-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_medicalhistory_prescribedmedicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Appointment Date'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Doctor Name'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Student ID'),
        ),
    ]
