# Generated by Django 6.0.3 on 2026-09-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_medicalhistory_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='appointment',
        ),
    ]
