# Generated by Django 6.0.3 on 2026-09-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_medicalhistory_appointment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prescribedmedicine',
            table='app_medhistory_medicines',
        ),
    ]
