# Generated by Django 6.0.3 on 2026-09-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_prescribedmedicine_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, help_text="e.g. 10 for a strip of 10 tablets. Leave as 1 if this medicine isn't received in packs/strips — stock always tracks individual units regardless.", verbose_name='Units per Pack/Strip'),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='food_timing',
            field=models.CharField(choices=[('BEFORE', 'Before Food'), ('AFTER', 'After Food'), ('WITH', 'With Food'), ('ANYTIME', 'Anytime')], default='AFTER', max_length=10),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='instructions',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='route',
            field=models.CharField(choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical / Apply'), ('DROPS', 'Drops'), ('INJECTION', 'Injection'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='ORAL', max_length=10),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='take_afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='take_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='take_morning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='take_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Visited'), ('NO_SHOW', 'No-Show'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Total Units Dispensed'),
        ),
        migrations.AlterField(
            model_name='todaysappointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Visited')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
