# Generated by Django 6.0.3 on 2026-09-27 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_medicine_pack_size_prescribedmedicine_dosage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_via', models.CharField(blank=True, default='', max_length=20)),
                ('sessions_cleared', models.PositiveIntegerField(default=0)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Maintenance',
                'verbose_name_plural': 'Site Maintenance',
            },
        ),
    ]
