# Generated by Django 6.0.3 on 2026-10-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_sitemaintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='message',
        ),
    ]
