# Generated by Django 6.0.3 on 2026-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_blooddonation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], default='MORNING', help_text="Select the doctor's working shift.", max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(blank=True, choices=[('08:00 AM', '08:00 AM'), ('08:30 AM', '08:30 AM'), ('09:00 AM', '09:00 AM'), ('09:30 AM', '09:30 AM'), ('10:00 AM', '10:00 AM'), ('10:30 AM', '10:30 AM'), ('11:00 AM', '11:00 AM'), ('11:30 AM', '11:30 AM'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('01:00 PM', '01:00 PM'), ('01:30 PM', '01:30 PM'), ('02:00 PM', '02:00 PM'), ('02:30 PM', '02:30 PM'), ('03:00 PM', '03:00 PM'), ('03:30 PM', '03:30 PM'), ('04:00 PM', '04:00 PM'), ('04:30 PM', '04:30 PM'), ('05:00 PM', '05:00 PM'), ('05:30 PM', '05:30 PM'), ('06:00 PM', '06:00 PM'), ('06:30 PM', '06:30 PM'), ('07:00 PM', '07:00 PM'), ('07:30 PM', '07:30 PM'), ('08:00 PM', '08:00 PM'), ('08:30 PM', '08:30 PM'), ('09:00 PM', '09:00 PM'), ('09:30 PM', '09:30 PM'), ('10:00 PM', '10:00 PM'), ('10:30 PM', '10:30 PM'), ('11:00 PM', '11:00 PM'), ('11:30 PM', '11:30 PM'), ('12:00 AM', '12:00 AM'), ('12:30 AM', '12:30 AM'), ('01:00 AM', '01:00 AM'), ('01:30 AM', '01:30 AM'), ('02:00 AM', '02:00 AM'), ('02:30 AM', '02:30 AM'), ('03:00 AM', '03:00 AM'), ('03:30 AM', '03:30 AM'), ('04:00 AM', '04:00 AM'), ('04:30 AM', '04:30 AM'), ('05:00 AM', '05:00 AM'), ('05:30 AM', '05:30 AM'), ('06:00 AM', '06:00 AM'), ('06:30 AM', '06:30 AM'), ('07:00 AM', '07:00 AM'), ('07:30 AM', '07:30 AM')], max_length=20, null=True, verbose_name='Preferred Time Slot'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(help_text="Comma-separated days, e.g. 'Monday, Tuesday, Wednesday'", max_length=200, verbose_name='Available Days'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(blank=True, help_text='Auto-filled from shift — do not edit manually.', max_length=100, verbose_name='Available Time'),
        ),
    ]
