# Generated by Django 6.0.3 on 2026-10-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_add_doctor_shift_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='shift',
        ),
        migrations.AddField(
            model_name='doctor',
            name='friday_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], max_length=10, null=True, verbose_name='Friday Shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='monday_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], max_length=10, null=True, verbose_name='Monday Shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='saturday_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], max_length=10, null=True, verbose_name='Saturday Shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sunday_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], max_length=10, null=True, verbose_name='Sunday Shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='thursday_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], max_length=10, null=True, verbose_name='Thursday Shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tuesday_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], max_length=10, null=True, verbose_name='Tuesday Shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='wednesday_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning Shift  (8:00 AM – 2:00 PM)'), ('EVENING', 'Evening Shift  (2:00 PM – 8:00 PM)'), ('NIGHT', 'Night Shift    (8:00 PM – 8:00 AM)')], max_length=10, null=True, verbose_name='Wednesday Shift'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(blank=True, help_text='Auto-filled from shifts — do not edit manually.', max_length=100, verbose_name='Available Time'),
        ),
    ]
