# Generated by Django 6.0.3 on 2026-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_doctor_available_days_remove_doctor_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning (8 AM - 2 PM)'), ('EVENING', 'Evening (2 PM - 8 PM)'), ('NIGHT', 'Night (8 PM - 8 AM)')], max_length=20, null=True, verbose_name='Preferred Shift'),
        ),
    ]
