# Generated by Django 6.0.3 on 2026-10-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='attending_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_histories', to='app.doctor', verbose_name='Attending Doctor'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='is_referred',
            field=models.BooleanField(default=False, verbose_name='Referred'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='referred_to',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Referred To'),
        ),
    ]
